[versions]
kotlin = "2.1.0"
openrndr = "0.4.5-alpha6"
orx = "0.4.5-alpha6"

[libraries]
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

openrndr-application = { group = "org.openrndr", name = "openrndr-application", version.ref = "openrndr" }
openrndr-dds = { group = "org.openrndr", name = "openrndr-dds", version.ref = "openrndr" }
openrndr-draw = { group = "org.openrndr", name = "openrndr-draw", version.ref = "openrndr" }
openrndr-webgl = { group = "org.openrndr", name = "openrndr-webgl", version.ref = "openrndr" }

[plugins]
kotlin-js = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
